### ISSUE TITLE
Escaping of apostrophes

### ISSUE THREAD

**Issue by andkopp** [objective-partner/abap_debugger_data_view_extension#10]
We ran into an issue that apostrophes in customer names are not escaped so the VALUE statement is invalid.

I would also suggest to move to string templates and add back slashes for the special characters like pipe and curly brackets. Here is an overview:
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/abenstring_templates_literals.htm

**Comment by gepparta** [comment]
Hi Andreas, do you have an example for this apostrophes issue?
It's ok, if there is already a corresponding unittest for it in your pull request, I will find it.

**Comment by gepparta** [comment]
Fixed with help of @andkopp in 5ccccd43b8382dd9ce8f5f58888ab99985dcab4d
