### ISSUE TITLE
Pretty printer factory is not regarding customizing

### ISSUE THREAD

**Issue by andkopp** [objective-partner/abap_debugger_data_view_extension#12]
Entries in table ZTOP_DVE_CUST are not considered when instantiating pretty printer class. The causes are that method read_customizing is not called and instantiation uses fix class name.

**Comment by gepparta** [comment]
Hi Andreas, 
you are right, there is a bug in create method of zcl_op_pretty_printer_factory.
Seems that my internal bitbucket coding looks different.

I will check your pull request and proceed there.

Kind regards
Alex

**Comment by gepparta** [comment]
Fixed with help of @andkopp in 5ccccd43b8382dd9ce8f5f58888ab99985dcab4d
