### ISSUE TITLE
Table ZTOP_DVE_CUST should be editable in non-dev system

### ISSUE THREAD

**Issue by andkopp** [objective-partner/abap_debugger_data_view_extension#14]
The table ZTOP_DVE_CUST should be modifiable in each system without transport request from development system.

**Comment by gepparta** [comment]
@andkopp Could you please check if given fix is resolving your issue?

**Comment by andkopp** [comment]
@gepparta I was not able to test it yet because our github connection seems to be broken.

**Comment by andkopp** [comment]
Editing the table does not require a transport request now. Thank you.
