### ISSUE TITLE
Extension requires ABAP 7.51 (enumerations)

### ISSUE THREAD

**Issue by AlexandreHT** [objective-partner/abap_debugger_data_view_extension#19]
Hello, 
```zcl_op_value_pretty_printer``` class uses enumerations that requires ABAP 7.51 (https://syntax.abaplint.org/?filter=typeenum) which is a real challenge (I work on a pretty up to date system and we're only 7.50).

Would agree to commit to go back to a 7.40 compatibility?

BR, 
Alexandre

**Comment by gepparta** [comment]
Hi Alexandre,

you are right.

I think we will create one branch for 7.40 and one for newer versions of ABAP component.

I will keep this ticket updated.

BR
Alex

**Comment by AlexandreHT** [comment]
Actually, I just did the work this morning. I seems to work (UT pass).

**Comment by gepparta** [comment]
Hi Alexandre,

please try first my fix in new available branch:
https://github.com/objective-partner/abap_debugger_data_view_extension/tree/ABAP-7.40

It has some more fixes than replacing ENUM.
See https://github.com/objective-partner/abap_debugger_data_view_extension/pull/18#issuecomment-804137589

Feedback welcome.

Kind regards
Alex

**Comment by AlexandreHT** [comment]
Hi Alex,
No issues while importing with ABAPgit. That's a good start.
Thanks 
Alexandre
