### ISSUE TITLE
Button "Data for ABAP View" is shown multiple times

### ISSUE THREAD

**Issue by christianguenter2** [objective-partner/abap_debugger_data_view_extension#2]
If I press on the top left button the custom button "Data for ABAP View" is added multiple times.

![image](https://user-images.githubusercontent.com/17437789/34127392-31bf92a8-e43d-11e7-8ddc-00853b87b9b5.png)

**Comment by gepparta** [comment]
Hello Christian, thank you. I will check that.

**Comment by gepparta** [comment]
Fixed with #3
