### ISSUE TITLE
ABAP Editor supports only 255 characters

### ISSUE THREAD

**Issue by andkopp** [objective-partner/abap_debugger_data_view_extension#9]
Hi Alex.
Thank your for your work on this project. I really appreciate it. 
We installed it today and ran into an issue when extracting IDoc data (edidd). The field sdata of an IDoc segment is defined as LCHR(1000). The created VALUE statement for the segments looks fine - but when we try to paste it into the ABAP editor it cannot be processed because a line can only contain 255 characters. This seems to be a limit with the editor.

My suggested solution would be to use several strings (string templates) and connect them via '&&' like this:
Line 1: var = |200 chars| && 
Line 2: |200 char|.

I would not go beyond 200 chars so that there is enough space for variable names and whitespaces.
Maybe I can fix this myself and provide a solution.

Best regards
Andreas

**Comment by andkopp** [comment]
I wrote a small, failing unit test in the class ZCL_OP_TABLE in order to make this issue more transparent:

    TYPES: BEGIN OF ty_segment,
             segnam(100) TYPE c,
             sdata(1000) TYPE c,
           END OF ty_segment.
    DATA lt_segments TYPE TABLE OF ty_segment WITH DEFAULT KEY.
    DATA lt_lines TYPE TABLE OF string WITH DEFAULT KEY.

    lt_segments = VALUE #(
      (
      segnam = 'E1EDK01'
      sdata = |EUREUR1.00000     0021             DE12345678901       DE12345678901       INVO1234561234| &&
              |                         2.000             2.000             ABCDE                       | &&
              |                              1112223344               ABCDEDFGHIJKLMNOPQRSTUVWXYZ       | &&
              |AND STILL SOME MORE CHARACTERS - THERE WILL BE NO END                                    | &&
              |                               - MAYBE THERE IS AN END IN SIGHT                          |
      )
    ).

    DATA(output) = table_view->prepare_output( i_table = lt_segments
                                               i_table_title = 'EDIDD' ).

    TRY.
        DATA(formatted) = zcl_op_pretty_printer_factory=>create( )->format( output ).

        SPLIT formatted AT zcl_op_value_pretty_printer=>c_newline INTO TABLE lt_lines.

        DATA(max_length) = 0.
        LOOP AT lt_lines INTO DATA(line).
          DATA(length) = strlen( line ).
          max_length = COND i( WHEN length >= max_length THEN length ELSE max_length ).
        ENDLOOP.

        cl_abap_unit_assert=>assert_number_between( lower = 0 upper = 255 number = max_length ).

      CATCH cx_class_not_existent.
    ENDTRY.

I think I will move the unit test to the pretty printer class and provide a solution there because it is more an issue with the pretty printer. The table class could return an unformatted value string with more than 255 characters and the pretty printer will have to get along with it - that means split up the string and add chaining characters. The pretty printer class is also responsible for the indents which also influence line length so it will fit best there - and it is also more an UI issue than an issue with the data.

This change will probably be more extensive than expected.

**Comment by gepparta** [comment]
Hi Andreas, you are right with pretty printer class. 
This Issue affects formatting data rather then retrieving it.

**Comment by gepparta** [comment]
Fixed with help of @andkopp  in 5ccccd43b8382dd9ce8f5f58888ab99985dcab4d
